import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Product } from '../interfaces/products.interface';

@Injectable({
  providedIn: 'root',
})
export class ShopService {
  private products: Product[] = [
    {
      name: 'Hoodie Hombre Gris',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 5,
      price: 100000,
      identifier: 'Hoodie Hombre Gris',
      img: '../../assets/img/store/55.png',
      qty: 1,
    },
    {
      name: 'Hoodie Hombre Azul Marino',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 6,
      price: 100000,
      identifier: 'Hoodie Hombre Azul Marino',
      img: '../../assets/img/store/6.png',
      qty: 1,
    },
    {
      name: 'Hoodie Hombre Negro',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 7,
      price: 100000,
      identifier: 'Hoodie Hombre Negro',
      img: '../../assets/img/store/7.png',
      qty: 1,
    },
    {
      name: 'Hoodie Hombre Blanco',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'airpods',
      id: 8,
      price: 100000,
      identifier: 'Hoodie Hombre Blanco',
      img: '../../assets/img/store/8.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Azul Marino',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 1,
      price: 100000,
      identifier: 'Hoodie Mujer Azul Marino',
      img: '../../assets/img/store/1.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Gris',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 2,
      price: 100000,
      identifier: 'Hoodie Mujer Gris',
      img: '../../assets/img/store/2.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Negro',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 3,
      price: 100000,
      identifier: 'Hoodie Mujer Negro',
      img: '../../assets/img/store/3.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Blanco',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 4,
      price: 100000,
      identifier: 'Hoodie Mujer Blanco',
      img: '../../assets/img/store/4.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Amarillo-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 9,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Amarillo-Blanco',
      img: '../../assets/img/store/9.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Azul-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 10,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Azul-Blanco',
      img: '../../assets/img/store/10.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Gris Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 11,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Gris Blanco',
      img: '../../assets/img/store/11.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Negro-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 12,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Negro-Blanco',
      img: '../../assets/img/store/12.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Rojo-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 13,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Rojo-Blanco',
      img: '../../assets/img/store/13.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Rojo-Negro',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 14,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Rojo-Negro',
      img: '../../assets/img/store/18.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Negro-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 15,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Negro-Gris',
      img: '../../assets/img/store/15.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Rojo-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 16,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Rojo-Gris',
      img: '../../assets/img/store/16.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Gris-Negro',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 17,
      price: 70000,
      identifier: 'Camisa Raglan Mujer Gris-Negro',
      img: '../../assets/img/store/17.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Gris-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 18,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Gris-Blanco',
      img: '../../assets/img/store/19.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Azul-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 19,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Azul-Blanco',
      img: '../../assets/img/store/20.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Negro-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 20,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Negro-Blanco',
      img: '../../assets/img/store/21.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Rojo-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 21,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Rojo-Blanco',
      img: '../../assets/img/store/22.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Negro-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 22,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Negro-Gris',
      img: '../../assets/img/store/24.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Rojo-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 23,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Rojo-Gris',
      img: '../../assets/img/store/25.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Gris-Negro',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 24,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Gris-Negro',
      img: '../../assets/img/store/26.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Negro-Rojo',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 25,
      price: 70000,
      identifier: 'Camisa Raglan Hombre Negro-Rojo',
      img: '../../assets/img/store/27.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Mujer Gris',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 26,
      price: 35000,
      identifier: 'Camiseta Básica Algodón Mujer Gris',
      img: '../../assets/img/store/28.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Hombre Gris',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 27,
      price: 35000,
      identifier: 'Camiseta Básica Algodón Hombre Gris',
      img: '../../assets/img/store/29.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Mujer Blanca',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 28,
      price: 35000,
      identifier: 'Camiseta Básica Algodón Mujer Blanca',
      img: '../../assets/img/store/30.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Hombre Blanca',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 29,
      price: 35000,
      identifier: 'Camiseta Básica Algodón Hombre Blanca',
      img: '../../assets/img/store/31.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Mujer Negra',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 30,
      price: 35000,
      identifier: 'Camiseta Básica Algodón Mujer Negra',
      img: '../../assets/img/store/32.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Hombre Negra',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 31,
      price: 35000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store/33.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 33,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/100-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 34,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/101-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 35,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/102-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 36,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/103-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 37,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/104-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 38,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/105-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 39,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/106-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 40,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/107-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 41,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/108-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 42,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/109-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 43,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/110-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 44,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/111-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 45,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/112-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 46,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/113-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 47,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/114-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 48,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/115-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 49,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/116-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 50,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/117-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 51,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/118-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta negra Demon Slayer',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 52,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/119-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 53,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/050-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 54,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/051-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 55,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/052-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 56,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/053-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 57,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/054-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 58,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/055-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 59,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/056-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 60,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/057-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 61,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/058-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 62,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/059-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 63,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/060-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 64,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/061-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 65,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/062-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 66,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/063-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 67,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/064-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Attack on Titan',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 68,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/065-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 69,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/150-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 70,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/151-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 71,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/152-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 72,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/153-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 73,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/154-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 74,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/155-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 75,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/156-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 76,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/157-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 77,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/158-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 78,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/159-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 79,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/160-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 80,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/161-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 81,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/162-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 82,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/163-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 83,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/164-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 84,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/165-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 85,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/166-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 86,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/167-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 87,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/168-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 88,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/169-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 89,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/170-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 90,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/171-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 91,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/172-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Berserk',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 92,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/173-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 93,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/001-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 94,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/002-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 95,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/003-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 96,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/004-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 97,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/005-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 98,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/006-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 99,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/007-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 100,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/008-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 101,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/009-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 102,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/010-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 103,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/011-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 104,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/012-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 105,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/013-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 106,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/014-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Evangelion',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 107,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/015-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta Bartman',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 108,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/200-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 109,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/201-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 110,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/202-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 111,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/203-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 112,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/204-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 113,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/205-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 114,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/206-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 115,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/207-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 116,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/208-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 117,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/209-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 118,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/210-min.png',
      qty: 1,
    },
    {
      name: 'Camiseta',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 119,
      price: 60000,
      identifier: 'Camiseta Básica Algodón Hombre Negra',
      img: '../../assets/img/store-prints/211-min.png',
      qty: 1,
    },
    {
      name: 'Estampado personalizado sencillo',
      description:'Estampado en la parte frontal o reversa, se aplica técnica de serigrafía obteniendo un estampado de calidad y duradero, diseño customizable.',
      category: 'Estampados',
      id: 150,
      price: 25000,
      identifier: 'Estampado Sencillo',
      img: '../../assets/img/store/34.png',
      qty: 1,
    },
    {
      name: 'Estampado personalizado doble',
      description:'Estampado en la parte frontal y reversa del torso, se aplica técnica de serigrafía obteniendo un estampado de calidad y duradero, diseño customizable.',
      category: 'Estampados',
      id: 151,
      price: 50000,
      identifier: 'Estampado Doble',
      img: '../../assets/img/store/35.png',
      qty: 1,
    },
    {
      name: 'Estampado personalizado triple',
      description:'Estampado en la parte frontal, reversa y mangas, se aplica técnica de serigrafía obteniendo un estampado de calidad y duradero, diseño customizable.',
      category: 'Estampados',
      id: 152,
      price: 70000,
      identifier: 'Estampado Triple',
      img: '../../assets/img/store/36.png',
      qty: 1,
    },
  ];

  constructor() {}

  getProducts(): Observable<Product[]> {
    return of(this.products);
  }
}
