import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Product } from '../interfaces/products.interface';

@Injectable({
  providedIn: 'root',
})
export class ShopService {
  private products: Product[] = [
    {
      name: 'Hoodie Hombre Gris',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 5,
      price: 100000,
      identifier: 'iPhone 14 128GB',
      img: '../../assets/img/store/55.png',
      qty: 1,
    },
    {
      name: 'Hoodie Hombre Azul Marino',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 6,
      price: 100000,
      identifier: 'AirPods 3rd generation',
      img: '../../assets/img/store/6.png',
      qty: 1,
    },
    {
      name: 'Hoodie Hombre Negro',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 7,
      price: 100000,
      identifier: 'AirPods Pro 2nd generation',
      img: '../../assets/img/store/7.png',
      qty: 1,
    },
    {
      name: 'Hoodie Hombre Blanco',
      description: 'Buso en algodón perchado Monaco, capucha con forro liso, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'airpods',
      id: 8,
      price: 100000,
      identifier: 'AirPods 2nd generation',
      img: '../../assets/img/store/8.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Azul Marino',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 1,
      price: 100000,
      identifier: 'Hoodie Azul Marino Mujer',
      img: '../../assets/img/store/1.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Gris',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 2,
      price: 100000,
      identifier: 'iPhone 14 Pro 128GB',
      img: '../../assets/img/store/2.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Negro',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 3,
      price: 100000,
      identifier: 'iPhone 14 Pro 1TB',
      img: '../../assets/img/store/3.png',
      qty: 1,
    },
    {
      name: 'Hoodie Mujer Blanco ',
      description: 'Buso en algodón perchado Monaco, capucha con forro afelpado, mangas y cintura en tela Reed, cordón de buen calibre y resistente, ojal y campana en acero inoxidable, costura frontal bolsillo - hombro, tallas XS - XL.',
      category: 'Hoodie',
      id: 4,
      price: 100000,
      identifier: 'iPhone 14 512GB',
      img: '../../assets/img/store/4.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Amarillo-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 9,
      price: 70000,
      identifier: '14‑inch MacBook Pro 16GB 512GB',
      img: '../../assets/img/store/9.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Azul-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 10,
      price: 70000,
      identifier: '14‑inch MacBook Pro 32GB 1TB',
      img: '../../assets/img/store/10.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Gris Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 11,
      price: 70000,
      identifier: '16‑inch MacBook Pro 16GB 512GB',
      img: '../../assets/img/store/11.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Negro-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 12,
      price: 70000,
      identifier: '16‑inch MacBook Pro 32GB 1TB',
      img: '../../assets/img/store/12.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Rojo-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 13,
      price: 70000,
      identifier: 'MacBook Air 8GB 256GB',
      img: '../../assets/img/store/13.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Blanco-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 14,
      price: 70000,
      identifier: 'MacBook Air 16GB 512GB',
      img: '../../assets/img/store/14.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Negro-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 15,
      price: 70000,
      identifier: 'iPad Air 64GB Wi-Fi',
      img: '../../assets/img/store/15.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Rojo-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 16,
      price: 70000,
      identifier: 'iPad Air 258GB Wi-Fi + Celular',
      img: '../../assets/img/store/16.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Gris-Negro',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 17,
      price: 70000,
      identifier: 'iPad Pro 11 128GB Wi-Fi',
      img: '../../assets/img/store/17.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Mujer Rojo-Negro',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 18,
      price: 70000,
      identifier: 'iPad Pro 11 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/18.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Gris-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 19,
      price: 70000,
      identifier: 'iPad Pro 12.9 128GB Wi-Fi',
      img: '../../assets/img/store/19.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Azul-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 20,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/20.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Negro-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 21,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/21.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Rojo-Blanco',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 22,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/22.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Blanco-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 23,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/23.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Negro-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 24,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/24.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Rojo-Gris',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 25,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/25.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Gris-Negro',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 26,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/26.png',
      qty: 1,
    },
    {
      name: 'Camisa Raglan Hombre Negro-Rojo',
      description:'Camisa en tela Circuito, colores customizables, cuello en tela Reed, manga larga - 3x4 - corta, cuello normal - bandeja para dama, gran detalle en terminados',
      category: 'Raglan',
      id: 27,
      price: 70000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/27.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Mujer Gris',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 28,
      price: 35000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/28.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Hombre Gris',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 29,
      price: 35000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/29.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Mujer Blanca',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 30,
      price: 35000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/30.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Hombre Blanca',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 31,
      price: 35000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/31.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Mujer Negra',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 32,
      price: 35000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/32.png',
      qty: 1,
    },
    {
      name: 'Camiseta Básica Algodón Hombre Negra',
      description:'Camiseta en algodón básica de calidad, gran detalle en terminados.',
      category: 'Camisetas',
      id: 33,
      price: 35000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/33.png',
      qty: 1,
    },
    {
      name: 'Estampado Sencillo Frente / Espalda',
      description:'Estampado en la parte frontal o reversa, se aplica técnica de serigrafía obteniendo un estampado de calidad y duradero, diseño customizable.',
      category: 'Estampados',
      id: 34,
      price: 25000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/34.png',
      qty: 1,
    },
    {
      name: 'Estampado Doble Frente y Espalda',
      description:'Estampado en la parte frontal y reversa, se aplica técnica de serigrafía obteniendo un estampado de calidad y duradero, diseño customizable.',
      category: 'Estampados',
      id: 35,
      price: 45000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/35.png',
      qty: 1,
    },
    {
      name: 'Estampado Triple Frente + Espalda + Mangas',
      description:'Estampado en la parte frontal, reversa y mangas, se aplica técnica de serigrafía obteniendo un estampado de calidad y duradero, diseño customizable.',
      category: 'Estampados',
      id: 36,
      price: 60000,
      identifier: 'iPad Pro 12.9 1TB Wi-Fi + Celular',
      img: '../../assets/img/store/36.png',
      qty: 1,
    },
  ];

  constructor() {}

  getProducts(): Observable<Product[]> {
    return of(this.products);
  }
}
